import type { ArtifactCandidateManifest, ArtifactIndex, EvolutionTrail, ResearchContract } from '../types.js';

export function createDefaultResearchContract(): ResearchContract {
  return {
    theme: 'Unspecified research theme',
    initial_question: 'Unspecified initial question',
    mode: 'human',
    scope: {
      in_scope: [],
      out_of_scope: [],
    },
    termination_type: 'best_effort',
  };
}

export function createDefaultEvolutionTrail(): EvolutionTrail {
  return {
    evolution_trail: [],
  };
}

export function createDefaultArtifactIndex(): ArtifactIndex {
  return {
    artifacts: [],
  };
}

export function createDefaultArtifactCandidateManifest(): ArtifactCandidateManifest {
  return {
    artifact_candidates: [],
  };
}

export function createDefaultResourcesMarkdown(): string {
  return [
    '# Project Resources',
    '',
    '## Research Theme',
    '',
    '- Theme statement: unspecified',
    '- Current biological focus: unspecified',
    '',
    '## Biological Background',
    '',
    '- Biological system: unspecified',
    '- Stable boundaries or assumptions: unspecified',
    '- Prior knowledge worth reusing: unspecified',
    '',
    '## Runtime Environments',
    '',
    '- Python: unspecified',
    '- R: unspecified',
    '- External tools / compute: unspecified',
    '',
    '## Data Resources',
    '',
    '- Linked datasets under `data/`: none yet',
    '- Primary datasets: unspecified',
    '- Supporting datasets: unspecified',
    '- Existing evidence assets: none listed yet',
    '',
    '## Local Skills',
    '',
    '- Validate task skills against `.codex/skills/`.',
    '- Mirror workflow and domain skills into `.claude/skills/` when Claude bootstrap is installed.',
    '- Keep task-level `skills:` for concrete domain dependencies only; do not list `qdd/*` workflow skills there.',
    '- Domain-specific local skills: none yet',
    '',
  ].join('\n');
}

export function createDefaultInstructionsMarkdown(): string {
  return [
    '# QDD Instructions',
    '',
    '## Quick Reference',
    '',
    '### Truth Sources',
    '',
    '- `contract.yaml` - research theme, scope, and authority mode',
    '- `evolution.yaml` - question evolution history',
    '- `context/resources.md` - default human-readable project resources',
    '- other `context/*.md` and `context/*.yaml` files - optional reusable context sidecars',
    '- `data/` - project-local dataset entrypoints; prefer symlinks, not copied raw data',
    '- `.codex/skills/` - project-local skill inventory used to validate task skill IDs',
    '- `.claude/skills/` - mirrored local skill surface for Claude-compatible bootstrap installs',
    '- `studies/STUDY-XXX/study.md` - bounded study definition',
    '- `studies/STUDY-XXX/tasks/TASK-XXX.md` - evidence-producing task definition',
    '- `studies/STUDY-XXX/output/artifact-candidates.yaml` - explicit promotion list for reusable study outputs',
    '- `artifacts/index.yaml` - reusable artifact registry',
    '',
    '### Installed Workflow Surfaces',
    '',
    '- `qdd-start` - onboard project context, dataset links, and local skills before the first study',
    '- `qdd-propose` - frame one bounded study from a human-supplied question or hypothesis',
    '- `qdd-explore` - stress-test the study and converge to a resource-supported plan',
    '- `qdd-apply` - execute within the active study until it reaches a decision point',
    '- `qdd-close` - validate, synthesize, carry forward stable context, and close the study',
    '',
    '### CLI Checkpoints',
    '',
    '- `qdd init` - install the scaffold and bootstrap surfaces; do not recreate them manually',
    '- `qdd status --json` - inspect the project-level dashboard before high-level decisions',
    '- `qdd instructions PROJECT --json` - inspect project onboarding bounds before changing shared context',
    '- `qdd instructions <id> --json` - use authoritative read/write bounds before editing a study or task',
    '- `qdd context --json` - inspect reusable project context',
    '- `qdd artifacts:list --json` - inspect reusable outputs before regenerating work',
    '- `qdd validate --json` - run before closure or a high-confidence handoff',
    '',
    '## Mode Contract',
    '',
    '### Shared Rules',
    '',
    '- Treat `contract.yaml.mode` as the authority signal for workflow behavior.',
    '- Treat YAML frontmatter as machine-readable truth and Markdown sections as execution guidance.',
    '- `study.md` and `task.md` are the template-constrained artifacts in this workflow slice.',
    '- Workflow prompts such as `qdd-propose`, `qdd-explore`, `qdd-apply`, and `qdd-close` guide reasoning and behavior; they are not rigid output schemas.',
    '- Only reference domain task skills that exist under `.codex/skills/`.',
    '- Keep task frontmatter `skills:` and the body `## Skills` section identical.',
    '- Only write evidence-backed, cross-study reusable knowledge into `context/` resources.',
    '',
    '### start',
    '',
    '1. Use `qdd instructions PROJECT --json` before editing shared project context.',
    '2. Fill `contract.yaml` and `context/resources.md` with real project facts rather than leaving scaffold placeholders.',
    '3. Add project dataset entrypoints under `data/` using symlinks instead of copying raw data.',
    '4. Treat `.codex/skills/` as the local skill validation inventory and `.claude/skills/` as the mirrored tool surface when installed.',
    '5. Stop when the project is ready for the first `qdd-propose` pass.',
    '',
    '### human',
    '',
    '- Humans own study-level direction and closure judgment.',
    '- `qdd-start` collects and structures project facts, but must not invent them.',
    '- `qdd-propose` writes the first-pass `study + initial task` directly when the direction is actionable.',
    '- `qdd-explore` is discussion-first and confirmation-gated before modifying study/task artifacts.',
    '- `qdd-apply` executes the current approved study/task set; if the plan itself needs reshaping, return to `qdd-explore`.',
    '- `qdd-close` remains human-approved before finalizing closure.',
    '',
    '### assist',
    '',
    '- Follow the same artifact authority boundaries as `human` mode.',
    '- `qdd-start` may draft more structure, but still depends on human-supplied project facts.',
    '- You may draft more concrete edits, task shapes, and closure reasoning, but still wait for confirmation before changing study/task artifacts in `qdd-explore` or finalizing closure.',
    '',
    '### auto',
    '',
    '- `qdd-start` may structure provided facts directly, but must not fabricate missing project context.',
    '- Proceed directly when the project and study context are sufficient.',
    '- `qdd-explore` may be merged into apply-time reasoning when the study is already actionable.',
    '- Keep plan growth minimal and stay inside the current study boundary.',
    '',
    '## Workflow',
    '',
    '### Start',
    '',
    '1. If the project is not initialized, run `qdd init` first.',
    '2. Read `qdd status --json` and `qdd instructions PROJECT --json`.',
    '3. Update `contract.yaml` and `context/resources.md` with the real research theme, biological background, runtime environment, and data availability.',
    '4. Create or refresh dataset entrypoints under `data/` using symlinks.',
    '5. Keep project-owned workflow and domain skills under the categorized `.codex/skills/` tree and do not reference missing local skills as if they already exist.',
    '',
    '### Propose',
    '',
    '1. If the project is not initialized, run `qdd init` first.',
    '2. If project context is still placeholder-level, complete `qdd-start` first.',
    '3. Read `qdd status --json` and, when useful, `qdd context --json` and `qdd artifacts:list --json`.',
    '4. Create or refresh one bounded `study.md` and one corresponding initial `TASK-XXX.md`.',
    '5. Use the study/task templates directly and rewrite placeholders into concrete first-pass content.',
    '6. Only write task skills that already exist under `.codex/skills/`, and keep them limited to concrete domain dependencies.',
    '7. Never write `qdd/*` workflow skills into task `skills:`.',
    '8. Do not turn propose into a long debate; later critique belongs in `qdd-explore`.',
    '',
    '### Explore',
    '',
    '1. Run `qdd instructions STUDY-XXX --json` before reshaping a study.',
    '2. Explore only options that remain relevant to the active study question and current task set.',
    '3. In `human` and `assist` mode, discuss and refine first; do not modify study/task files until the user confirms.',
    '4. Converge to a resource-supported plan: worth doing, feasible now, blockers, evidence plan, and task shape.',
    '5. Stop when the study is executable, explicitly blocked, or ready for approved edits.',
    '',
    '### Apply',
    '',
    '1. Treat the study as the execution unit.',
    '2. Run `qdd instructions STUDY-XXX --json` first, then `qdd instructions TASK-XXX --json` for the current approved task set.',
    '3. If a task declares missing local skills, hard-block execution until the skill is installed under `.codex/skills/` or the task is rewritten.',
    '4. Rewrite the weak task checklist scaffold into task-specific executable steps before or during execution.',
    '5. Update study and task Markdown directly while the work progresses.',
    '6. Package local evidence under `studies/STUDY-XXX/output/{code,figures,tables,reports}/` when those output types are produced.',
    '7. Record promotion-worthy outputs in `studies/STUDY-XXX/output/artifact-candidates.yaml` or register them immediately when appropriate.',
    '8. Continue until the study reaches a decision point, explicit blocker, or boundary change that should return to `qdd-explore`.',
    '',
    '### Close',
    '',
    '1. Run `qdd validate --json` before closure or handoff.',
    '2. Synthesize evidence from the study, tasks, outputs, and registered artifacts.',
    '3. Register any missing reusable outputs listed in `studies/STUDY-XXX/output/artifact-candidates.yaml` before closure.',
    '4. Use `qdd close-study` to record `question_delta` in `evolution.yaml`.',
    '5. Update stable `context/` resources directly when the evidence is reusable across studies.',
    '6. Suggest next studies, but do not create them automatically.',
    '',
    '## Validation Checklist',
    '',
    '- Did you call `qdd status --json` before making high-level project judgments?',
    '- Did you call `qdd instructions PROJECT --json` before changing shared project context or dataset entrypoints?',
    '- Did you call `qdd instructions <id> --json` before editing an existing study or task?',
    '- Did you preserve YAML frontmatter at the top of every managed Markdown file?',
    '- Did project dataset entrypoints under `data/` use symlinks instead of copied raw data?',
    '- Did every task-level skill reference resolve under `.codex/skills/`?',
    '- Did every task-level skill list avoid `qdd/*` workflow skills?',
    '- Did task frontmatter `skills:` stay identical to the body `## Skills` section?',
    '- Did you keep one bounded question per study?',
    '- Did you keep `study.md` and `task.md` as the only template-constrained artifacts?',
    '- Did `qdd-propose` create a concrete first-pass study and initial task?',
    '- Did `qdd-explore` stay discussion-first in `human` and `assist` mode?',
    '- Did `qdd-apply` execute the current approved study/task set rather than defaulting to plan redesign?',
    '- Did you rewrite the weak task checklist scaffold into task-specific executable steps?',
    '- Did substantive analyses leave behind readable scripts in `studies/STUDY-XXX/output/code/`?',
    '- Did visual claims leave behind key figures in `studies/STUDY-XXX/output/figures/` or explicitly state why no figure was needed?',
    '- Did promoted outputs come from the explicit study candidate list rather than blind output scanning?',
    '- Did every reusable output get registered with explicit provenance?',
    '- Did you keep context updates stable, evidence-backed, and reusable across studies?',
    '',
    '## Advanced Notes',
    '',
    '- Use `refinement`, `confirmation`, `pivot`, or `dissolution` when generating `question_delta`.',
    '- `context/` is an open context directory; Markdown is the default human-readable format, and YAML remains optional for structured sidecars.',
    '- `.codex/skills/` is the task-skill validation inventory, and `.claude/skills/` mirrors the same relative IDs when Claude bootstrap is installed.',
    '- Only categorized skill IDs such as `qdd/qdd-propose` or `plot/marker-heatmap` participate in the QDD local inventory.',
    '- `data/` is for dataset entrypoints and should usually contain symlinks rather than copied payloads.',
    '- `qdd-explore` may discuss alternatives, but it must return to the active study question before it ends.',
    '- In this slice, workflow prompt source may live in repo-local Markdown files used by the bootstrap generator.',
    '- The default task checklist scaffold is intentionally weak and should be rewritten for the real task.',
    '- `artifact-candidates.yaml` is the explicit promotion boundary between local study outputs and reusable artifacts.',
    '- There is no separate `qdd-project` wrapper in this slice.',
    '- There is no assist-mode planner, learned-rules engine, or automatic next-study creation yet.',
    '',
  ].join('\n');
}
