#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ensure_cache_layout.sh [PROJECT_ROOT]

Prepare a project-local cache layout for sandboxed Python/R analysis and
write .qdd/cache-env.sh with recommended environment exports.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

project_root="${1:-.}"

if [[ ! -d "$project_root" ]]; then
  echo "Project root does not exist: $project_root" >&2
  exit 1
fi

project_root="$(cd "$project_root" && pwd)"

cache_root="$project_root/.cache"
qdd_root="$project_root/.qdd"
env_file="$qdd_root/cache-env.sh"

mkdir -p \
  "$cache_root/matplotlib" \
  "$cache_root/numba" \
  "$cache_root/xdg" \
  "$cache_root/tmp" \
  "$qdd_root"

cat >"$env_file" <<EOF
#!/usr/bin/env bash
# Generated by env/fix-cache-layout.
export XDG_CACHE_HOME="$cache_root/xdg"
export MPLCONFIGDIR="$cache_root/matplotlib"
export NUMBA_CACHE_DIR="$cache_root/numba"
export TMPDIR="$cache_root/tmp"
EOF

chmod 755 "$env_file"

printf 'Prepared project-local cache layout under %s\n' "$cache_root"
printf 'Generated env exports: %s\n' "$env_file"
printf '\n'
printf 'Load before analysis:\n'
printf '  source %q\n' "$env_file"
