import type { ManagedFileContract } from './shared.js';

export function createDefaultResourcesMarkdown(): string {
  return [
    '# Project Resources',
    '',
    '## Research Theme',
    '',
    '- Theme statement: unspecified',
    '- Current biological focus: unspecified',
    '',
    '## Biological Background',
    '',
    '- Biological system: unspecified',
    '- Stable boundaries or assumptions: unspecified',
    '- Prior knowledge worth reusing: unspecified',
    '',
    '## Data Resources',
    '',
    '- Linked datasets under `artifacts/data/`: none yet',
    '- Primary datasets: unspecified',
    '- Supporting datasets: unspecified',
    '- Existing evidence assets: none listed yet',
    '',
    '## Runtime Environments',
    '',
    '- Python: unspecified',
    '- R: unspecified',
    '- External tools / compute: unspecified',
    '',
    '## Analyst Preferences',
    '',
    '- Stable methodological preferences: unspecified',
    '- Evidence preferences: unspecified',
    '- Long-lived cautions or anti-patterns: unspecified',
    '- Preferred reusable environment or tool constraints: unspecified',
    '',
    '## Local Skills',
    '',
    '- Treat `brain/*` as domain-prior sidecars and planning-time guidance.',
    '- Treat non-`brain/*` skills with metadata as executor-facing problem-level skills.',
    '- Use public-data planning only when local resources are insufficient or an external validation/reference dataset is genuinely needed.',
    '- Keep external dataset search results small and explicit; record only final selected targets in study-local handoff files.',
    '- For lightweight public-data capture such as markers, ligand-receptor pairs, GEO candidate tables, or PubMed evidence tables, keep the search intent in the task and materialize the chosen CSV/TSV directly; do not force them through public_data_request.yaml.',
    '- Validate task skills against the QDD root `domain-skills/` library and `.qdd/skills-catalog.json`.',
    '- Keep workflow skills under local `.codex/skills/qdd/` and mirror those workflow skills into `.claude/skills/qdd/` when Claude bootstrap is installed.',
    '- Keep task-level `skills:` for concrete problem-level dependencies only; do not list `qdd/*` or `brain/*` there.',
    '- Use `.qdd/layer-policy.yaml` for command -> role mapping and role-level default skills.',
    '- Domain-specific local skills: none yet',
    '',
  ].join('\n');
}

export function createExampleResourcesMarkdown(): string {
  return [
    '# Project Resources',
    '',
    '## Research Theme',
    '',
    '- Theme statement: discover reusable tumor-reactive T cell evidence across studies',
    '- Current biological focus: T cell state structure in checkpoint blockade response',
    '',
    '## Biological Background',
    '',
    '- Biological system: tumor and blood immune compartments',
    '- Stable boundaries or assumptions: focus on transcriptomic evidence before wet-lab interpretation',
    '- Prior knowledge worth reusing: tumor-reactive T cell programs and integration sensitivity across patients',
    '',
    '## Data Resources',
    '',
    '- Linked datasets under `artifacts/data/`: GSE-example-primary.h5ad',
    '- Primary datasets: one multi-patient h5ad with sample metadata',
    '- Supporting datasets: external validation dataset pending',
    '- Existing evidence assets: one prior integration script and one previous study memory file',
    '',
    '## Runtime Environments',
    '',
    '- Python: qdd-skill-core with scanpy and scib installed',
    '- R: not required for the current loop',
    '- External tools / compute: CPU okay for planning, GPU not required',
    '',
    '## Analyst Preferences',
    '',
    '- Stable methodological preferences: prefer scanpy-native first-pass workflows',
    '- Evidence preferences: preserve scripts and key figures for every substantive analysis step',
    '- Long-lived cautions or anti-patterns: do not replace integration with unrelated clustering heuristics',
    '- Preferred reusable environment or tool constraints: preserve sparse h5ad matrices when possible',
    '',
    '## Local Skills',
    '',
    '- Study planning should read brain skills before proposing executor skills.',
    '- Executor tasks should use only problem-level skills already indexed in `.qdd/skills-catalog.json`.',
    '- Public-data acquisition should stay explicit and small; do not download broad candidate sets by default.',
    '- Dataset handoffs and lightweight public-data capture tasks are different: only dataset-style public-data tasks need `public_data_request.yaml`.',
    '',
  ].join('\n');
}

export const resourcesFileContract: ManagedFileContract = {
  id: 'resources',
  title: 'context/resources.md',
  projectPath: 'context/resources.md',
  exampleFileName: 'resources.example.md',
  format: 'markdown',
  purpose: 'Human-readable project memory for durable resources, environments, and preferences.',
  sections: [
    { name: 'Research Theme', required: true, description: 'Stable project-level research framing.' },
    { name: 'Biological Background', required: true, description: 'Domain facts and assumptions worth carrying forward.' },
    { name: 'Data Resources', required: true, description: 'Linked datasets, evidence assets, and data entrypoints.' },
    { name: 'Runtime Environments', required: true, description: 'Relevant Python, R, and external tooling constraints.' },
    { name: 'Analyst Preferences', required: true, description: 'Durable methodological preferences or cautions.' },
    { name: 'Local Skills', required: true, description: 'How local skill surfaces should be interpreted.' },
  ],
  notes: [
    'Keep only durable, reusable context here.',
    'Per-study narrative belongs in context/memory/STUDY-XXX.md.',
  ],
  renderExample: () => `${createExampleResourcesMarkdown().trim()}\n`,
};
